### ISSUE TITLE
possible improvement?

### ISSUE THREAD

**Issue by minektur** [DoomHammer/brewstrap#2]
One idea I had is that for each of the unix command line tools that is a dependency (e.g. as listed in README.md) - you might use each of those commands 'bare' with no path and then put in your instructions that the user's path needs to include each dependency.  In fact, early on in the script you could test for each of those and complain..  

This would make your script work in a much wider variety of weird os configurations...

**Comment by DoomHammer** [comment]
I don't think I totally understand this. Do you mean something like #5?

**Comment by minektur** [comment]
Your solution for #5 was better than what I suggested and solves the same problem.
