### ISSUE TITLE
missing file command in chromeos causes bottle-installs to hang

### ISSUE THREAD

**Issue by minektur** [DoomHammer/brewstrap#8]
you should include a build of homebrew-dupes/file-forumula package in your initial package or bottles fail.  Or perhaps recommend installing from source with --build-from-source as the first package after install...

**Comment by DoomHammer** [comment]
`file-formula` is there, see https://github.com/DoomHammer/brewstrap/blob/master/brewstrap.sh#L42 . Before that `file` distributed with `brewstrap` should be used (`$BREWSTRAP_DIR/bin/file`). If there is something I might have ommitted feel free to reopen this issue.
